server {
    listen 80;
    server_name localhost;

    # Sirve los archivos estáticos de React (Corregido)
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Redirige los fetch de tu main.jsx al backend real
    location /api {
        proxy_pass http://192.168.56.101.sslip.io;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}